# TODO(simon0191): Move this to /vm and remove all unnecessary files
# frozen_string_literal: true
source 'https://supermarket.chef.io'

metadata

# General
cookbook 'system', '~> 0.11.3'
cookbook 'apt', '~> 7.1.1'
cookbook 'build-essential', '~> 8.2.1'

# Ruby
cookbook 'ruby_rbenv', '~> 2.1.1'

# Code editors
cookbook 'vim', '~> 2.0.2'
